name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Add conda to PATH
      shell: bash
      if: startsWith(matrix.os, 'macOS') || startsWith(matrix.os, 'ubuntu')
      run: echo "::add-path::$CONDA/bin"
    - name: Add conda to PATH
      shell: bash
      if: startsWith(matrix.os, 'windows')
      run: echo "::add-path::$CONDA\Scripts"
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    - name: Create environment for package
      shell: bash
      run: |
        conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=${{ matrix.python-version }} devtools/conda-envs/test_env.yaml
    - name: Install package
      shell: bash
      run: |
        conda activate test
        pip install . --no-deps
    - name: Lint with flake8
      shell: bash
      run: |
        conda activate test
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      shell: bash
      run: |
        conda activate test
        pytest -v --cov=kinoml kinoml/tests/
    - name: Code coverage
      shell: bash
      run: |
        conda activate test
        codecov