name: MkDocs

on:
  push:
    branches:
      - master
      - mkdocs

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Create environment for package
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate
          python devtools/scripts/create_conda_env.py -n=docs -p=3.7 devtools/conda-envs/test_env.yaml
          conda activate docs
          python -m pip install . --no-deps

      - name: Build docs
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate docs
          mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site